let iqHash = []
const iqHash1 =['ClosePrice',
    'OriginalListPrice',
    'CloseDate',
    'PriceChangeTimestamp',
    'iqDownloadName',
    'PropertySubType',
    'BedroomsTotal',
    'LotSizeArea',
    'LotSizeAcres',
    'UnparsedAddress',
    'MLSAreaMajor',
    'iqStatus',
    'InternetAddressDisplayYN',
    'Basement',
    'Bathrooms',
    'BathroomsTotalInteger',
    'BathroomsFull',
    'BathroomsHalf',
    'BathroomsPartial',
    'BathroomsThreeQuarter',
    'bayFeedId',
    'bay_OriginalEntryTimestamp',
    'BuildingName',
    'NumberOfBuildings',
    'TotalBuildings',
    'BuyerAgentMlsId',
    'BuyerAgentFullName',
    'BuyerAgentFirstName',
    'BuyerAgentLastName',
    'BuyerOfficeMlsId',
    'BuyerOfficeName',
    'CarportSpaces',
    'GarageCarport',
    'City',
    'InternetAutomatedValuationDisplayYN',
    'SubdivisionName',
    'CountyOrParish',
    'OriginalEntryTimestamp',
    'OnMarketDate',
    'CumulativeDaysOnMarket',
    'DaysOnMarket',
    'PublicRemarks',
    'SecurityDeposit',
    'Disclaimer',
    'ExpirationDate',
    'feed_id',
    'Flooring',
    'SpecialListingConditions',
    'GarageType',
    'GarageCapacity',
    'GarageSpaces',
    'AssociationAmenities',
    'CommunityFeatures',
    'ExteriorFeatures',
    'View',
    'AssociationYN',
    'AssociationFee',
    'AssociationFeeIncludes',
    'AssociationFeeFrequency',
    'iqImages',
    'Latitude',
    'ListPrice',
    'SearchPrice',
    'LivingArea',
    'PricePerSquareFoot',
    'ListingAgentIdxEmail',
    'ListAgentEmail',
    'CoListAgentEmail',
    'ListAgentMlsId',
    'CoListAgentMlsId',
    'ListAgentFullName',
    'ListAgentFirstName',
    'ListAgentLastName',
    'CoListAgentFullName',
    'CoListAgentFirstName',
    'CoListAgentLastName',
    'ListingAgentIdxPhone',
    'ListAgentPreferredPhone',
    'CoListAgentPreferredPhone',
    'ListingKey',
    'ListingKeyNumeric',
    'ListOfficeEmail',
    'OfficeEmail',
    'CoListOfficeEmail',
    'ListOfficeMlsId',
    'CoListOfficeMlsId',
    'ListOfficeName',
    'CoListOfficeName',
    'ListOfficePhone',
    'CoListOfficePhone',
    'URL',
    'PropertyType',
    'Longitude',
    'iqMlsId',
    'OriginatingSystemName',
    'iqMlsNumber',
    'ModificationTimestamp',
    'ParkingTotal',
    'ParkingFeatures',
    'PetsAllowed',
    'PoolPrivateYN',
    'PoolFeatures',
    'iqDownloadTimestamp',
    'HighSchoolDistrict',
    'ElementarySchool',
    'ElementarySchoolDistrict',
    'MiddleOrJuniorSchool',
    'MiddleOrJuniorSchoolDistrict',
    'HighSchool',
    'ShortSaleYN',
    'smcFeedId',
    'RetailSqFt',
    'OfficeSqFt',
    'State',
    'StateOrProvince',
    'StandardStatus',
    'bay_status',
    'MlsStatus',
    'Stories',
    'StoriesTotal',
    'Levels',
    'Subdistrict',
    'AnnualTaxes',
    'NumberOfUnitsTotal',
    'VirtualTourURL',
    'VirtualTourURLBranded',
    'VirtualTourURLUnbranded',
    'FrontageType',
    'YearBuilt',
    'PostalCode',
    'zip_code',
    'Zoning',
    'ZoningDetails',
    'ZoningDescription',
    'StreetNumberNumeric',
    'StreetDirPrefix',
    'StreetName',
    'StreetDirSuffix',
    'StreetSuffix',
    'UnitNumber',
    'Unit1FullBaths',
    'Unit1PartialBaths',
    'Unit2FullBaths',
    'Unit2PartialBaths',
    'Unit3FullBaths',
    'Unit3PartialBaths',
    'Unit4FullBaths',
    'Unit4PartialBaths',
    'Unit1Bedrooms',
    'Unit2Bedrooms',
    'Unit3Bedrooms',
    'Unit4Bedrooms',
    'Appliances',
    'InteriorFeatures',
    'Cooling',
    'Heating',
    'FireplaceFeatures',
    'FireplacesTotal',
    'LaundryFeatures',
    'WindowFeatures',
    'RoomsTotal',
    'Furnished',
    'Roof',
    'FoundationDetails',
    'LotFeatures',
    'PatioAndPorchFeatures',
    'Fencing',
    'ConstructionMaterials',
    'SecurityFeatures',
    'SeniorCommunityYN',
    'Utilities',
    'Sewer',
    'Electric',
    'Floor',
    'BuildingAreaTotal',
    'SchoolDistrictCounty']

iqHash1?.forEach((item) => {
    if(!iqHash?.includes(item)){
        iqHash.push(item)
    }
})

console.log("iqHash", iqHash)


// ClosePrice,
// OriginalListPrice,
// CloseDate,
// PriceChangeTimestamp,
// iqDownloadName,
// PropertySubType,
// BedroomsTotal,
// LotSizeArea,
// LotSizeAcres,
// UnparsedAddress,
// MLSAreaMajor,
// iqStatus,
// InternetAddressDisplayYN,
// Basement,
// Bathrooms,
// BathroomsTotalInteger,
// BathroomsFull,
// BathroomsHalf,
// BathroomsPartial,
// BathroomsThreeQuarter,
// bayFeedId,
// bay_OriginalEntryTimestamp,
// BuildingName,
// NumberOfBuildings,
// TotalBuildings,
// BuyerAgentMlsId,
// BuyerAgentFullName,
// BuyerAgentFirstName,
// BuyerAgentLastName,
// BuyerOfficeMlsId,
// BuyerOfficeName,
// CarportSpaces,
// GarageCarport,
// City,
// InternetAutomatedValuationDisplayYN,
// SubdivisionName,
// CountyOrParish,
// OriginalEntryTimestamp,
// OnMarketDate,
// CumulativeDaysOnMarket,
// DaysOnMarket,
// PublicRemarks,
// SecurityDeposit,
// Disclaimer,
// ExpirationDate,
// feed_id,
// Flooring,
// SpecialListingConditions,
// GarageType,
// GarageCapacity,
// GarageSpaces,
// AssociationAmenities,
// CommunityFeatures,
// ExteriorFeatures,
// View,
// AssociationYN,
// AssociationFee,
// AssociationFeeIncludes,
// AssociationFeeFrequency,
// iqImages,
// Latitude,
// ListPrice,
// SearchPrice,
// LivingArea,
// PricePerSquareFoot,
// ListingAgentIdxEmail,
// ListAgentEmail,
// CoListAgentEmail,
// ListAgentMlsId,
// CoListAgentMlsId,
// ListAgentFullName,
// ListAgentFirstName,
// ListAgentLastName,
// CoListAgentFullName,
// CoListAgentFirstName,
// CoListAgentLastName,
// ListingAgentIdxPhone,
// ListAgentPreferredPhone,
// CoListAgentPreferredPhone,
// ListingKey,
// ListingKeyNumeric,
// ListOfficeEmail,
// OfficeEmail,
// CoListOfficeEmail,
// ListOfficeMlsId,
// CoListOfficeMlsId,
// ListOfficeName,
// CoListOfficeName,
// ListOfficePhone,
// CoListOfficePhone,
// URL,
// PropertyType,
// Longitude,
// iqMlsId,
// OriginatingSystemName,
// iqMlsNumber,
// ModificationTimestamp,
// ParkingTotal,
// ParkingFeatures,
// PetsAllowed,
// PoolPrivateYN,
// PoolFeatures,
// iqDownloadTimestamp,
// HighSchoolDistrict,
// ElementarySchool,
// ElementarySchoolDistrict,
// MiddleOrJuniorSchool,
// MiddleOrJuniorSchoolDistrict,
// HighSchool,
// ShortSaleYN,
// smcFeedId,
// RetailSqFt,
// OfficeSqFt,
// State,
// StateOrProvince,
// StandardStatus,
// bay_status,
// MlsStatus,
// Stories,
// StoriesTotal,
// Levels,
// Subdistrict,
// AnnualTaxes,
// NumberOfUnitsTotal,
// VirtualTourURL,
// VirtualTourURLBranded,
// VirtualTourURLUnbranded,
// FrontageType,
// YearBuilt,
// PostalCode,
// zip_code,
// Zoning,
// ZoningDetails,
// ZoningDescription
// StreetNumberNumeric,
// StreetDirPrefix,
// StreetName,
// StreetDirSuffix,
// StreetSuffix,
// UnitNumber,
// Unit1FullBaths,
// Unit1PartialBaths,
// Unit2FullBaths,
// Unit2PartialBaths,
// Unit3FullBaths,
// Unit3PartialBaths,
// Unit4FullBaths,
// Unit4PartialBaths,
// Unit1Bedrooms,
// Unit2Bedrooms,
// Unit3Bedrooms,
// Unit4Bedrooms,
// Appliances,
// InteriorFeatures,
// Cooling,
// Heating,
// FireplaceFeatures,
// FireplacesTotal,
// LaundryFeatures,
// WindowFeatures,
// RoomsTotal,
// Furnished,
// Roof,
// FoundationDetails,
// LotFeatures,
// PatioAndPorchFeatures,
// Fencing,
// ConstructionMaterials,
// SecurityFeatures,
// SeniorCommunityYN,
// Utilities,
// Sewer,
// Electric,
// Floor,
// BuildingAreaTotal,
// SchoolDistrictCounty,